// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class MathTest {
	  private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  @Before
	  public void setUp() {
		  System.setProperty("webdriver.chromedriver","C:\\Users\\besti\\eclipse-workspace\\TriangleTest\\chromedriver.exe"); //Путь до ChromeDriver
	   
		  ChromeOptions opt = new ChromeOptions();
		  opt.addArguments("--headless");
		  
		  driver = new ChromeDriver(opt);
	 
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
  @Test
  public void mathTest1() {
    // Test name: MathTest1
    // Step # | name | target | value
    // 1 | open | https://www.calculator.net/math-calculator.html | 
    driver.get("https://www.calculator.net/math-calculator.html");
    // 2 | click | css=div:nth-child(3) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(3) > .scinm:nth-child(1)")).click();
    // 3 | click | css=div:nth-child(1) > .sciop:nth-child(4) | 
    driver.findElement(By.cssSelector("div:nth-child(1) > .sciop:nth-child(4)")).click();
    // 4 | click | css=div:nth-child(3) > .scinm:nth-child(2) | 
    driver.findElement(By.cssSelector("div:nth-child(3) > .scinm:nth-child(2)")).click();
    // 5 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 6 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 7 | click | css=div:nth-child(2) > .sciop:nth-child(4) | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .sciop:nth-child(4)")).click();
    // 8 | click | css=div:nth-child(3) > .scinm:nth-child(2) | 
    driver.findElement(By.cssSelector("div:nth-child(3) > .scinm:nth-child(2)")).click();
    // 9 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 10 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 11 | click | css=div:nth-child(3) > .sciop:nth-child(4) | 
    driver.findElement(By.cssSelector("div:nth-child(3) > .sciop:nth-child(4)")).click();
    // 12 | click | css=div:nth-child(2) > .scinm:nth-child(2) | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .scinm:nth-child(2)")).click();
    // 13 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 14 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 15 | click | css=div:nth-child(4) > .sciop:nth-child(4) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .sciop:nth-child(4)")).click();
    // 16 | click | css=div:nth-child(2) > .scinm:nth-child(2) | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .scinm:nth-child(2)")).click();
    // 17 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 18 | click | css=div:nth-child(4) > .scinm:nth-child(1) | 
    driver.findElement(By.cssSelector("div:nth-child(4) > .scinm:nth-child(1)")).click();
    // 19 | click | css=.scieq:nth-child(4) | 
    driver.findElement(By.cssSelector(".scieq:nth-child(4)")).click();
    // 20 | assertText | id=sciOutPut |  1
    assertEquals(driver.findElement(By.id("sciOutPut")).getText()," 1");
  }
}
